<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerUfkbtln\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerUfkbtln/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerUfkbtln.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerUfkbtln\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerUfkbtln\appDevDebugProjectContainer(array(
    'container.build_hash' => 'Ufkbtln',
    'container.build_id' => 'c4a06aea',
    'container.build_time' => 1519744072,
));
